name: CI

on: push

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run a multi-line script
      run: |
        chmod +x gradlew
        ./gradlew shadow
        
    - name: upload
      with:
        name: ReefAutoUpdate.jar
        path: build/libs/*.jar
